sudo: false
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V

services:
  - postgresql

before_script:
  - psql -c 'create database jpgstreamstore;' -U postgres

notifications:
  email: false

branches:
  only:
    - master
